apiVersion: apps/v1
kind: Deployment
metadata: 
  name: redis-deploy
  labels:
    name: redis-deploy
    app: demo-volting-app
spec:
  replica: 1
  selector:
    matchLabels:
      name: redis-pod
      app: demo-volting-app
  template:
    metadata: 
      name: redis-pod
      labels:
        name: redis-pod
        app: demo-volting-app
    spec:
      container:
        - name: redis
          image: redis
          ports: 
          - containerPort: 6379
    
    
  
         