apiVersion: v1
kind: Pod
metadata: 
  name: result-app-pod
  labels:
    name: result-app-pod
    app: demo-volting-app
spec:
  container:
    - name: result-app
      image: kodecloud/examplevotingapp_result:v1
      ports: 
       - containerPort: 80
         