apiVersion: v1
kind: Pod
metadata: 
  name: worker-pod
  labels:
    name: worker-pod
    app: demo-voting-app
spec:
  container:
    - name: worker-app
      image: kodecloud/examplevotingapp_vote:v1
      
         